const ageRangeData = [
  { value: '20', label: '20' },
  { value: '21', label: '21' },
  { value: '22', label: '22' },
  { value: '23', label: '23' },
  { value: '24', label: '24' },
  { value: '25', label: '25' },
  { value: '26', label: '26' },
  { value: '27', label: '27' },
  { value: '28', label: '28' },
  { value: '29', label: '29' },
  { value: '30', label: '30' },
  { value: '31', label: '31' },
  { value: '32', label: '32' },
  { value: '33', label: '33' },
];

const bodyTypeData = [
  { value: '마름', label: '마름' },
  { value: '슬림', label: '슬림' },
  { value: '탄탄', label: '탄탄' },
  { value: '보통', label: '보통' },
  { value: '통통', label: '통통' },
  { value: '근육질', label: '근육질' },
];

const departmentData = [
  { value: '공과대학', label: '공과대학' },
  { value: '사범대학', label: '사범대학' },
  { value: '사회과학대학', label: '사회과학대학' },
  { value: '경영대학', label: '경영대학' },
  { value: '문과대학', label: '문과대학' },
  { value: '이과대학', label: '이과대학' },
  { value: '건축대학', label: '건축대학' },
  { value: '부동산과학원', label: '부동산과학원' },
  { value: 'KU융합과학기술원', label: 'KU융합과학기술원' },
  { value: '상허생명과학대학', label: '상허생명과학대학' },
  { value: '수의과대학', label: '수의과대학' },
];

const addressData = [
  { value: '강남구', label: '강남구' },
  { value: '강동구', label: '강동구' },
  { value: '강북구', label: '강북구' },
  { value: '강서구', label: '강서구' },
  { value: '관악구', label: '관악구' },
  { value: '광진구', label: '광진구' },
  { value: '구로구', label: '구로구' },
  { value: '금천구', label: '금천구' },
  { value: '노원구', label: '노원구' },
  { value: '도봉구', label: '도봉구' },
  { value: '동대문구', label: '동대문구' },
  { value: '동작구', label: '동작구' },
  { value: '마포구', label: '마포구' },
  { value: '서대문구', label: '서대문구' },
  { value: '서초구', label: '서초구' },
  { value: '성동구', label: '성동구' },
  { value: '성북구', label: '성북구' },
  { value: '송파구', label: '송파구' },
  { value: '양천구', label: '양천구' },
  { value: '영등포구', label: '영등포구' },
  { value: '용산구', label: '용산구' },
  { value: '은평구', label: '은평구' },
  { value: '종로구', label: '종로구' },
  { value: '중구', label: '중구' },
  { value: '중랑구', label: '중랑구' },
  { value: '경기', label: '경기' },
  { value: '인천', label: '인천' },
];

const characterData = [
  { value: '시크', label: '시크' },
  { value: '다정', label: '다정' },
  { value: '활발', label: '활발' },
  { value: '무던', label: '무던' },
  { value: '세심', label: '세심' },
  { value: '이성적', label: '이성적' },
  { value: '감성적', label: '감성적' },
];

const mbtiData = [
  { value: 'INTP', label: 'INTP' },
  { value: 'INTJ', label: 'INTJ' },
  { value: 'ISFP', label: 'ISFP' },
  { value: 'ISTP', label: 'ISTP' },
  { value: 'ISTJ', label: 'ISTJ' },
  { value: 'ISFJ', label: 'ISFJ' },
  { value: 'INFP', label: 'INFP' },
  { value: 'INFJ', label: 'INFJ' },
  { value: 'ENTP', label: 'ENTP' },
  { value: 'ENTJ', label: 'ENTJ' },
  { value: 'ENFP', label: 'ENFP' },
  { value: 'ENTJ', label: 'ENTJ' },
  { value: 'ESTP', label: 'ESTP' },
  { value: 'ESTJ', label: 'ESTJ' },
  { value: 'ESFP', label: 'ESFP' },
  { value: 'ESFJ', label: 'ESFJ' },
];

const hobbyData = [
  { value: '걷기', label: '걷기' },
  { value: '헬스', label: '헬스' },
  { value: '여행', label: '여행' },
  { value: '등산', label: '등산' },
  { value: '축구', label: '축구' },
  { value: '배구', label: '배구' },
  { value: '농구', label: '농구' },
  { value: '야구', label: '야구' },
  { value: '자전거', label: '자전거' },
  { value: '달리기', label: '달리기' },
  { value: '마라톤', label: '마라톤' },
  { value: '유도', label: '유도' },
  { value: '태권도', label: '태권도' },
  { value: '권투', label: '권투' },
  { value: '무에타이', label: '무에타이' },
  { value: '검도', label: '검도' },
  { value: '댄스', label: '댄스' },
  { value: '등산', label: '등산' },
  { value: '산책', label: '산책' },
  { value: '수영', label: '수영' },
  { value: '수상스키', label: '수상스키' },
  { value: '서핑', label: '서핑' },
  { value: '보드게임', label: '보드게임' },
  { value: '스키', label: '스키' },
  { value: '테니스', label: '테니스' },
  { value: '베드민턴', label: '베드민턴' },
  { value: '요가', label: '요가' },
  { value: '공예', label: '공예' },
  { value: '그림', label: '그림' },
  { value: '요리', label: '요리' },
  { value: '자수', label: '자수' },
  { value: '뜨개질', label: '뜨개질' },
  { value: '사진 찍기', label: '사진 찍기' },
  { value: '서예', label: '서예' },
  { value: '글쓰기', label: '글쓰기' },
  { value: '패션', label: '패션' },
  { value: '쇼핑', label: '쇼핑' },
  { value: '게임', label: '게임' },
  { value: '블로그', label: '블로그' },
  { value: '골동품 수집', label: '골동품 수집' },
  { value: '맛집 탐방', label: '맛집 탐방' },
  { value: '재테크', label: '재테크' },
  { value: '바이올린', label: '바이올린' },
  { value: '기타', label: '기타' },
  { value: '드럼', label: '드럼' },
  { value: '피아노', label: '피아노' },
  { value: '코인노래방', label: '코인노래방' },
  { value: '오버워치', label: '오버워치' },
  { value: '롤', label: '롤' },
  { value: '발로란트', label: '발로란트' },
  { value: '메이플', label: '메이플' },
  { value: '카트라이더', label: '카트라이더' },
  { value: '롤토체스', label: '롤토체스' },
  { value: '서든어택', label: '서든어택' },
  { value: '마인크래프트', label: '마인크래프트' },
  { value: '술', label: '술' },
  { value: '풋살', label: '풋살' },
  { value: '배틀그라운드', label: '배틀그라운드' },
];

const drinkData = [
  { value: '음주 안 함', label: '음주 안 함' },
  { value: '종종', label: '종종' },
  { value: '애주가', label: '애주가' },
];

const smokeData = [
  { value: '흡연 안 함', label: '흡연 안 함' },
  { value: '종종', label: '종종' },
  { value: '애연가', label: '애연가' },
];

const priorityData = [
  { value: '나이', label: '나이' },
  { value: '학과', label: '학과' },
  { value: '주소', label: '주소' },
  { value: '취미', label: '취미' },
  { value: '성격', label: '성격' },
  { value: '체형', label: '체형' },
  { value: '흡연 정도', label: '흡연 정도' },
  { value: '음주 정도', label: '음주 정도' },
  { value: 'MBTI', label: 'MBTI' },
];

export { ageRangeData, bodyTypeData, departmentData, addressData, characterData, mbtiData, hobbyData, drinkData, smokeData, priorityData };
